"""Pydantic models for request/response validation."""

from __future__ import annotations

from pydantic import BaseModel, Field


# ── Request ──────────────────────────────────────────────────────────────────

class AnalyzeRequest(BaseModel):
    """Body accepted by POST /analyze."""

    height: float = Field(..., gt=0, description="Height in centimetres")
    weight: float = Field(..., gt=0, description="Weight in kilograms")
    calories: float = Field(..., ge=0, description="Daily calorie intake (kcal)")
    protein: float = Field(..., ge=0, description="Daily protein intake (grams)")
    fibre: float = Field(..., ge=0, description="Daily fibre intake (grams)")


# ── AI Plan (returned by Groq) ───────────────────────────────────────────────

class AIPlan(BaseModel):
    """Structured fitness plan generated by the LLM."""

    goal: str
    diet_plan: str
    workout_plan: str
    timeline: list[str]


# ── Response ─────────────────────────────────────────────────────────────────

class AnalyzeResponse(BaseModel):
    """Full response returned by POST /analyze."""

    bmi: float
    category: str
    ai_plan: AIPlan
    nutrition_feedback: list[str]
    images: list[str] = Field(
        default_factory=list,
        description="Up to 2 Base64-encoded fitness images",
    )
